export const lectures = [
  {
    date: "1/24",
    class: "1",
    topic: "Course Intro, Basic Engine Architecture, Camera and Game Loops",
    googleSlides: "slides",
    codeDemos: "demo",
    worksheets: "",
  },
  {
    date: "1/31",
    class: "2",
    topic: "Applications and Screens",
    googleSlides: "slides",
    codeDemos: "demo",
    worksheets: "",
  },
  {
    date: "2/7",
    class: "3",
    topic: "Game Worlds, Entity Component System, Collisions Intro",
    googleSlides: "slides",
    codeDemos: "demo",
    worksheets: "",
  },
  {
    date: "2/14",
    class: "4",
    topic: "Sphere/AAB/Cylinder Collisions, Ellipsoid/Triangle Collisions",
    googleSlides: "slides",
    codeDemos: "",
    worksheets: "worksheet",
  },
  {
    date: "2/21",
    class: "5",
    topic: "GJK, EPA, and MPR Algorithms",
    googleSlides: "slides",
    codeDemos: "",
    worksheets: "worksheet",
  },
  {
    date: "2/28",
    class: "",
    topic: "No Lecture - Extra Hours Instead",
    googleSlides: "",
    codeDemos: "",
    worksheets: "",
  },
  {
    date: "3/6",
    class: "6",
    topic: "Spatial Acceleration Data Structures",
    googleSlides: "slides",
    codeDemos: "",
    worksheets: "",
  },
  {
    date: "3/13",
    class: "8",
    topic: "AI and Pathfinding",
    googleSlides: "slides",
    codeDemos: "",
    worksheets: "",
  },
  {
    date: "3/20",
    class: "9",
    topic: "Platformer 3 Check-In",
    googleSlides: "",
    codeDemos: "",
    worksheets: "",
  },
  {
    date: "3/27",
    class: "",
    topic: "🌷 Spring Break - No Class 🌷",
    googleSlides: "",
    codeDemos: "",
    worksheets: "",
  },
  {
    date: "4/3",
    class: "10",
    topic: "Final Project Topics",
    googleSlides: "slides",
    codeDemos: "",
    worksheets: "",
  },
  {
    date: "4/10",
    class: "11",
    topic: "Final Project Check-In 1",
    googleSlides: "",
    codeDemos: "",
    worksheets: "",
  },
  {
    date: "4/17",
    class: "12",
    topic: "👽 Q&A with Mobius Digital 👽",
    googleSlides: "",
    codeDemos: "",
    worksheets: "",
  },
  {
    date: "4/24",
    class: "13",
    topic: "Final Project Check-In 2",
    googleSlides: "",
    codeDemos: "",
    worksheets: "",
  },
  {
    date: "5/9",
    class: "14",
    topic: "Final Project Presentations at 5 PM",
    googleSlides: "",
    codeDemos: "",
    worksheets: "",
  },
];
